### ISSUE TITLE
Pusher integration

### ISSUE THREAD

**Issue by datitisev** [FriendsOfFlarum/polls#5]
> It would be cool to add pusher integration to see real time results
> 
> — https://github.com/ReFlar/polls/issues/7

**Comment by clarkwinkelmann** [comment]
This was apparently implemented last year in https://github.com/FriendsOfFlarum/polls/commit/1a37975aa480defb5785099cf6a7eda54086f0c7

However that code didn't seem to work with Pusher as the imported namespace was invalid (`Pusher\Pusher` instead of expected `Pusher`).

I have pushed a fix and successfully tested Pusher integration in version 0.3.3 and 0.4.0
